<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitd08dcd1e9fb5806a9b8b15e476b54a67
{
    public static $prefixLengthsPsr4 = array (
        'W' => 
        array (
            'Workerman\\' => 10,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Workerman\\' => 
        array (
            0 => __DIR__ . '/..' . '/workerman',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitd08dcd1e9fb5806a9b8b15e476b54a67::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitd08dcd1e9fb5806a9b8b15e476b54a67::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitd08dcd1e9fb5806a9b8b15e476b54a67::$classMap;

        }, null, ClassLoader::class);
    }
}
